version: '3'
services:
  ddosgridapi:
    ports:
      - "8080:8080"
    build: "."
    volumes:
      - userdata:/usr/src/app/api/data/
    command:
      - /usr/src/app/api/scripts/start_demo_left.sh
  ddosgridfrontend:
    ports:
      - "8081:8081"
    build: "./frontend/Dockerfile-left"
    command: npm run serve
volumes:
  userdata:
