version: '3'
services:
  ddosgridapi:
    ports:
      - "8080:8080"
    build: "."
    volumes:
      - userdata:/usr/src/app/api/data/
    command:
      - /usr/src/app/api/scripts/start_dev_server.sh
  ddosgridfrontend:
    ports:
      - "8081:80"
    build: "./frontend"
volumes:
  userdata:
